export const EDITOR_TEXT = {
  undo: '撤销',
  redo: '重做',
  heading: '标题',
  paragraph: '正文',
  quote: '引用',
  codeBlock: '代码块',
  textColor: '文字颜色',
  highlightColor: '高亮颜色',
  bold: '加粗',
  italic: '斜体',
  underline: '下划线',
  inlineCode: '行内代码',
  alignLeft: '左对齐',
  alignCenter: '居中',
  alignRight: '右对齐',
  bulletList: '无序列表',
  orderedList: '有序列表',
  taskList: '任务列表',
  outdent: '减少缩进',
  indent: '增加缩进',
  uploadImage: '上传图片',
  uploadingImage: '正在处理图片…',
  insertImageByUrl: '通过 URL 插入图片',
  insertTable: '插入表格',
  addRowBefore: '上方插入行',
  addRowAfter: '下方插入行',
  deleteRow: '删除行',
  addColumnBefore: '左侧插入列',
  addColumnAfter: '右侧插入列',
  deleteColumn: '删除列',
  deleteTable: '删除表格',
  toolbarHint: '支持粘贴、拖拽或上传图片',
  insertLink: '插入链接',
  clearFormatting: '清除格式',
  exitFullscreen: '退出全屏',
  fullscreen: '全屏编辑',
  readImageFailed: '读取图片失败',
  decodeImageFailed: '图片解码失败',
  browserProcessImageUnsupported: '浏览器不支持图片处理',
  imageUrlPrompt: '图片 URL',
  imageUrlPlaceholder: 'https://...',
  linkUrlPrompt: '链接 URL',
  linkUrlPlaceholder: 'https://...',
  linkOpenInNewTab: '在新标签页打开',
  insertedImages: '已插入 ',
  imageUnit: ' 张图片',
  insertImageFailed: '插入图片失败',
  editorPlaceholder: '输入内容，或输入 / 查看命令',
  characters: '字',
  cancel: '取消',
  confirm: '确定',
  remove: '移除',
  modalLinkTitle: '插入链接',
  modalImageTitle: '插入图片',
  preview: '预览',
  slashHeading1: '一级标题',
  slashHeading2: '二级标题',
  slashHeading3: '三级标题',
  slashBulletList: '项目符列表',
  slashOrderedList: '有序列表',
  slashTaskList: '任务列表',
  slashQuote: '引用',
  slashCodeBlock: '代码块',
  slashDivider: '分隔线',
  slashTable: '表格',
  slashImage: '图片',
  slashSearchEmpty: '未找到匹配项',
  codeBlockLangPlaceholder: '语言',
  codeBlockLangPlain: '纯文本',
  imagePlaceholderHint: '图片处理中…',
} as const
